# .github/workflows/java-hello-world.yml

name: Java CI

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main

# Define the jobs to be run
jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Java 11
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      # Step 3: Compile the Java program
      - name: Compile Java Program
        run: javac HelloWorld.java

      # Step 4: Run the Java program
      - name: Run Java Program
        run: java HelloWorld
